title:            Ηａϲｋеｒｓ４Ϝｕｎ ᏟᎢＦ Τеａⅿ
description:      Proyecto fomenta la ciberseguridad a través de retos CTF propuestos con fines educativos para aprender a mejorar la seguridad en Internet. El conocimiento que se compartirá, todos ellos dirigidos a una práctica ética, si los usa para prácticas inadecuadas o de acuerdo con la legislación, será de su exclusiva responsabilidad. No somos responsables del mal uso que se puede dar a las herramientas y habilidades que se comparten.
disqus_shortname:
reading_time:     true
words_per_minute: 200
# Your site's domain goes here (eg: https://mmistakes.github.io, http://yourdomain.com, etc)
# When testing locally leave blank or use http://localhost:4000
url:               https://hackers4f.github.io

# Owner/author information
owner:
  name:           Hackers4f
  avatar:         avatar.jpg
  bio:            "Your bio goes here. It shouldn't be super long but a good sentence or two should suffice."
  email:          hackers4functfteam@gmail.comm
  # Social networking links used in footer. Update and remove as you like.
  twitter:        H4ck3rs4FunCTF
  facebook:       H4ck3rs4FunCTF
  github:         hackers4f
  stackexchange:
  linkedin:
  instagram:      H4ck3rs4FunCTF
  flickr:
  tumblr:
  # google plus id, include the '+', eg +mmistakes
  google_plus:

# Background image to be tiled on all pages
background:

# Analytics and webmaster tools stuff goes here
google_analytics:
google_verify:
# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
timezone:    Europe/Madrid
future:      true  # publish future dated posts --  true, false (default)
highlighter: rouge
markdown:    kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-feed
sass:
  sass_dir: _sass
  style: compressed

# https://github.com/mojombo/jekyll/wiki/Permalinks
permalink:   pretty

# Amount of post to show on home page
paginate: 5

kramdown:
  input: GFM
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

include:
  - .htaccess
exclude:
  - "*.less"
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - config
  - gulpfile.js
  - lib
  - log
  - node_modules
  - package.json
  - spec
  - tmp
